name: Django CI (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t iot-sensor-app -f sensingGang/Dockerfile sensingGang

    - name: Run tests inside container
      run: |
        docker run --rm iot-sensor-app sh -c "
          python manage.py migrate &&
          python manage.py test
        "
